sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Sjp333ZJLJOMSzpVwk2nDtlVj82+iRX3xCuxekrkYedRbggNhBozKILyDFCM/erTXuc+abtPZD+Jn3pPctBa0IdEph5DKjpyciuAkoFdkpuKgilogLN3Q51H43rxxa9uE7tUhYHk/o/b8KzW6+1bjZhvrd5OWXFtGUi+0dgOLerLRcKm4HSrQ0gseJl73tRviK9Amf2B+EP/e2a+l5kwvtPA+KVcrrCLB9b6bwdxm2RWwmyLKqQhgN+beuCdGUzkhHENOu80QzqfQS7e9qR39TU+RvnlQ50ZF+HGWeiU7EkD5F6vrseGAEgtsQwLxUFN+mCUrvq3hOdphnNgPhF6mlLaNRyTNpfokNR8kpkQ0+NhXoqvkyjQQvIEiJddLYleaBlgziXB43SmkCcts38zmxZLYYqxt/ThsIstwsLzOBG+j94Cqrn0vkSUIE/isaqtP7wSuCbnE3mLfLR5GXCPOkDG/3L2eKhnWYrTaCQmdVl4+LSygbvCTRLyiynBksnoI0bfhZt7QTBTCy+gJp2xBnk5X4Y6O44dLg5RHhxihlkYYZH6NHqmrtGL4+5R15n6TC89C12/kh4D9liEfx42ero3G7hX7dvpxQXPsxhy4JfiaakhvF8oKlx2QZKtMOyURqd/YM7HhkhjwhJAnxUcTVQ5TdCOQMsVGdU1qRf3Hm4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Memoirs-of-Carwin-the-Biloquist--A-Fragment-_842
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy